### ISSUE TITLE
gulp-nsp TypeError: callback is not a function

### ISSUE THREAD

**Issue by Wtower** [Wtower/gulpfile-ninecms#6]
When running the nsp method:

```
gkarak@rodope ~/w/n/yeotests> gulp nsp
[13:55:26] Using gulpfile ~/workspace/node/yeotests/gulpfile.js
[13:55:26] Starting 'nsp'...
[13:55:26] Finished 'nsp' after 24 ms
[13:55:27] (+) No known vulnerabilities found
/home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/index.js:49
      return callback();
             ^

TypeError: callback is not a function
    at /home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/index.js:49:14
    at /home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/node_modules/nsp/lib/check.js:233:7
    at /home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:472:20
    at finish (/home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/node_modules/nsp/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/home/gkarak/workspace/node/yeotests/node_modules/gulp-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:481:14)
    at afterWrite (_stream_writable.js:355:3)
    at nextTickCallbackWithManyArgs (node.js:464:18)
    at process._tickDomainCallback (node.js:403:17)
```

**Comment by Wtower** [comment]
Specify an empty function before calling.
